sudo: required
services:
  - docker

before_install:
  - docker build -t nkwochidubem/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nkwochidubem/react-test npm run test -- --watchAll=false

after_success:
  - docker build -t nkwochidubem/multi-client ./client 
  - docker build -t nkwochidubem/multi-server ./server 
  - docker build -t nkwochidubem/multi-worker ./worker 
  - docker build -t nkwochidubem/multi-nginx ./nginx 

  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_ID" --password-stdin

  # Push production images to docker Hub
  - docker push nkwochidubem/multi-client
  - docker push nkwochidubem/multi-nginx
  - docker push nkwochidubem/multi-server
  - docker push nkwochidubem/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-469839539849
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

